### ISSUE TITLE
Comand in form-vali

### ISSUE THREAD

**Issue by tobiasbianchi** [thinkingview/respiratorio#4]
generalmente mando como parametro el comando y por ahora estoy usando un input invisible...
Borrar los datos despues de enviados me borra ese input y no lo puedo usar mas.
Habria que hacerlo parte del form

**Comment by franciclo** [comment]
no podes usar el comando como hacias con la web api? me parece mas correcto hacer /comando?key=value

sino habria que modificar el uso del atributo direction de form-vali

**Comment by tobiasbianchi** [comment]
ya lo modifique como dijiste desde el .ashx
